### ISSUE TITLE
"Please Update. You are running an old version" message on output image

### ISSUE THREAD

**Issue by DiSonDS** [vasilysinitsin/Faces#6]
"Please Update!
You are running an old version. Please update FaceApp to the latest one."

**Comment by frozyeah** [comment]
I updated him, get working version - https://github.com/frozyeah/Faces

**Comment by vasilysinitsin** [comment]
Hello!
Thanks for contributing this one. I will close discussion here so it can be continued in PR section.

**Comment by TheEssem** [comment]
I found that the user agent now needs to be `FaceApp/3.2.2 (Linux; Android 8.1)`, and the URL needs to be changed to `https://node-03.faceapp.io/api/v2.11/photos`. They also changed the JSON in the newer versions, so instead of `body.filters`, you would use `body.objects[0].children`. The fixes have already been applied in [faceapp.js](https://github.com/lolPants/faceapp.js).

**Comment by vasilysinitsin** [comment]
@TheEssemCraft thanks for the reference. @re1ard had fixed that and master branch now is operational.

**Comment by DiSonDS** [comment]
It is still relevant

**Comment by shashitechno** [comment]
Stil getting same error.

**Comment by Dimentio** [comment]
Ditto.
